"""
Simple Example — Generated Output
====================================

This file shows what the **output** of ``APIBuilder`` looks like.

It was generated by running::

    from main import APIBuilder

    builder = APIBuilder("test", "https://google.com")
    builder.add_endpoint("test", "json", "get")
    print(builder.get_code())

You would normally save this output to its own ``.py`` file and run it
as a standalone Flask application.
"""

from flask import Flask
import requests
from json import loads

app: Flask = Flask(__name__)


def json(x):
    """Parse a JSON string and return the resulting Python object."""
    return loads(x)


def test():
    """Fetch https://google.com and return the parsed JSON response."""
    return json(requests.get("https://google.com").text)
